version: '3.9'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vblog_development
    env_file:
      - .envrc
    networks:
      - vblog_network
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/vblog_development
      LANG: en_US.UTF-8
      RAILS_SERVE_STATIC_FILES: enabled
    env_file:
      - .envrc
    command: rails s -b 0.0.0.0 -p 8085 -e ${RAILS_ENV}
    networks:
      - vblog_network
    ports:
      - "8085:8085"
    volumes:
      - ./:/root/app

networks:
  vblog_network:

volumes:
  db-data:
