version: '3.9'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: vblog_development
      PGPORT: ${DATABASE_PORT}
    networks:
      - vblog_network
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      DATABASE_URL: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/vblog_development
      GITHUB_KEY: ${GITHUB_KEY}
      GITHUB_SECRET: ${GITHUB_SECRET}
      LANG: en_US.UTF-8
      RACK_ENV: ${RACK_ENV}
      RAILS_ENV: ${RAILS_ENV}
      RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT}
      RAILS_SERVE_STATIC_FILES: enabled
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    command: rails s -b 0.0.0.0 -p 8085 -e ${RAILS_ENV}
    networks:
      - vblog_network
    ports:
      - "8085:8085"
    volumes:
      - ./:/root/app

networks:
  vblog_network:

volumes:
  db-data:
