version: '3.9'

services:
  db:
    image: postgres:15-alpine

    environment:
      PGPORT: ${DATABASE_PORT}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: vblog_development

    env_file:
      - .env

    network_mode: host

    restart: unless-stopped

    volumes:
      - db-data:/var/lib/postgresql/data
      - ./tmp:/tmp

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@localhost:${DATABASE_PORT}/vblog_development
      LANG: en_US.UTF-8
      RAILS_SERVE_STATIC_FILES: enabled
    env_file:
      - .env
    command: rails s -b 0.0.0.0 -p 8085 -e ${RAILS_ENV}

    network_mode: host

    volumes:
      - ./:/root/app

volumes:
  db-data:
